### ISSUE TITLE
Falta de uma network para os containers

### ISSUE THREAD

**Issue by ThalesMendes** [arquivei/laravel-skeleton-api#8]
Olhando no `docker-compose.yml`, não há uma network padrão para os containers se comunicarem. 

Podemos colocar algo assim para já ficar pronto pra quem for utilizar:
```yaml
networks:
    default:
        external:
            name: ${APP_IDENTIFIER}-network
```

E já adicionar a criação dessa network no `make setup` pra não ter problema no `up`:
`docker network create ${APP_IDENTIFIER}-network`

Fazendo assim, outro detalhe que pode ajudar também seria já deixar no `env.dist` a variável `DB_HOST` direto como `database`.
